galaxy_info:
  author: alpegon3@upv.es
  description: Install Apache Tomcat7
  company: GRyCAP
  license: Apache
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  - name: Ubuntu
    versions:
    - trusty
    - xenial
  galaxy_tags:
    - tomcat

dependencies: []
